<?php

/**
 * @file
 * This module holds functions and hooks useful for the module.
 */

use \Drupal\glyphicons\Plugin\CKEditorPlugin\Glyphicons;

/**
 * Implements hook_library_info_alter().
 */
function glyphicons_library_info_alter(&$libraries, $extension) {
  if ($extension === 'glyphicons' && isset($libraries['glyphicons'])) {
    $path = Glyphicons::getLibraryPath();
    $libraries['glyphicons']['css']['component'][$path . '/css/style.css'] = [];
  }
}
